### PR TITLE
make gateway optional

### PR DESCRIPTION
**Pull request by antimack**
Make installing gateway resources optional, this is needed in case if users having their own Ingress controller.

### CODE REVIEW

**Comment by unguiculus** [comment]
Not sure about that. You will always have an ingress controller. You should create an ingress for the gateway service instead of disabling it. Have you considered that?

**Comment by antimack** [comment]
When we create our namespace we usually provision it with Nginx Ingress controller, we are using official helm chart, so we can put any annotation, basic or oauth etc. In this case we do not need gateway deployment/service/configmap/pdb/secret as I understand or did I miss something? We do need Ingress resource and your helm chart has toggle for it so we will use it for sure.

**Comment by unguiculus** [comment]
The gateway is Loki's reverse proxy for all its components. It deals with all the Loki internals exposing the API and proxying to the indivudual components. IMHO, the ingress controller should not even have this knowledge. What I'm trying to say is that you should create an ingress for the gateway. The ingress controller would then only have to forward to the gateway and would not have to deal with Loki-specific Nginx configuration.

**Comment by unguiculus** [comment]
That being said, the Helm chart already supports ingress for the gateway. Are you aware of that?

**Comment by antimack** [comment]
ah! damn! now I am feeling bad of doing unneeded work :) I thought that gateway is just some generic Nginx but now I get your point, it's the part of the components and I do can use our Ingress controller to point to it's service via Ingress resource

**Comment by antimack** [comment]
thanks for an explanation!

**Comment by unguiculus** [comment]
No worries. Thanks for using the chart.

**Comment by antimack** [comment]
Thanks for a good chart, I really hope it will be merged to upstream soon ;)

**Pull request closed without merging**
